const LinkedList = require('./linked-list.js')

console.log('----- Create, append and print -----')
const list = new LinkedList()
list.append(1); list.append(2); list.append(3); list.append(4); list.append(5)
console.log('Print list:', list.toString())
console.log('List size:', list.size)

console.log('\n----- Print node by index -----')
console.log('Index is invalid:', list.at('x'))
console.log('Index is negative:', list.at(-1))
console.log('Index 0:', list.at(0))
console.log('Index 4:', list.at(4))
console.log('Index 5 (out of range):', list.at(5))

console.log('\n----- Head and tail -----')
console.log('Head:', list.head)
console.log('Tail:', list.tail)

console.log('\n----- Pop some nodes -----')
list.pop()
console.log('Print list after pop:', list.toString())
console.log('List size:', list.size)
list.pop(); list.pop(); list.pop()
console.log('Print list after three pops:', list.toString())
console.log('List size:', list.size)
console.log('Head:', list.head)
console.log('Tail:', list.tail)
list.pop()
console.log('Print list after final pop:', list.toString())
console.log('List size:', list.size)
console.log('Head:', list.head)
console.log('Tail:', list.tail)

list.append(1); list.append(2); list.append(3); list.append(4); list.append(5)
console.log('List repopulated:', list.toString())

console.log('\n----- List contains -----')
console.log('List contains 2:', list.contains(2))
console.log('List contains 9:', list.contains(9))

console.log('\n----- Find index by value -----')
console.log('Find:', list.find(4))
console.log('Find:', list.find(9))

console.log('\n----- Insert node at index -----')
console.log('Print list:', list.toString())
list.insertAt(77, 4)
console.log('Inserted 77 at index 4:', list.toString())
list.insertAt(99, 9)
console.log('Tried to insert 99 invalid index 9 (no change):', list.toString())

console.log('\n----- Remove node at index -----')
console.log('Print list:', list.toString())
list.removeAt(2)
console.log('Removed node at index 2', list.toString())
list.removeAt(0)
console.log('Removed node at index 0', list.toString())
list.removeAt(9)
console.log('Tried to node at invalid index 9 (no change)', list.toString())
list.removeAt(3)
console.log('Removed last node at index 3', list.toString())
